# Generated by Django 4.0.1 on 2022-06-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Body', models.TextField()),
                ('Slug', models.SlugField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
